from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('register',views.register,name="register"),
    path('login',views.login_page,name="login"),
    path('logout',views.logout_page,name="logout"),
    path('cart',views.cart_page,name="cart"),
    path('fav',views.fav_page,name="fav"),
    path('favviewpage',views.favviewpage,name="favviewpage"),
    path('remove_fav/<str:fid>',views.remove_fav,name="remove_fav"),
    path('remove_cart/<str:cid>',views.remove_cart,name="remove_cart"),
    path('collections',views.collections,name="collections"),
    path('collections/<str:name>',views.collectionsview,name="collections"),
    path('collections/<str:cname>/<str:pname>',views.product_details,name="product_details"),
    path('addtocart',views.add_to_cart,name="addtocart"),
    path('product/<int:id>/', views.product_detail_by_id, name='product_detail_by_id'),
    path('products/', views.product_list, name='product_list'),
    path('search', views.search, name='search'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('buy-now', views.buy_now, name="buy_now"),
    path('checkout', views.checkout, name="checkout"),
    path('save-address/', views.save_address, name="save_address"),
    path('address/', views.address_page, name='address'),
    path('place-order/', views.place_order, name='place_order'),
    path("payment/", views.payment, name="payment"),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("order-success/", views.order_success, name="order_success"),
    path('my-orders/', views.my_orders, name="my_orders"),
    path('order/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('order/<int:order_id>/', views.order_details, name='order_details'),
    path('dashboard/orders/', views.admin_orders, name='admin_orders'),
    path('dashboard/order/<int:order_id>/', views.admin_order_details, name='admin_order_details'),
    path('dashboard/order/<int:order_id>/status/', views.update_order_status, name='update_order_status'),
    path('order/<int:order_id>/invoice/', views.download_invoice, name='download_invoice'),
]