# Generated by Django 5.1.4 on 2025-12-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_app',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
