# Generated by Django 5.1.4 on 2025-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='upi_app',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
