# Generated by Django 5.1.4 on 2025-12-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_upi_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='upi_app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
